services:
  postgres:
    image: 'postgres:13'
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=my_store
      - POSTGRES_USER=johan
      - POSTGRES_PASSWORD=admin123
    ports:
      - 6543:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=johancalr11@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    depends_on:
      - postgres

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql
    ports:
      - 3307:80
    depends_on:
      - mysql
